name: movie_app
description: "A movie app built with Flutter using Clean Architecture and MobX"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter

  # State Management
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # Navigation
  go_router: ^14.6.3

  # Network
  dio: ^5.7.0

  # Local Storage
  shared_preferences: ^2.3.4

  # Image Caching
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # MobX Code Generation
  build_runner: ^2.4.14
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - .env
